version: "3.8"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:${DOCKER_INFLUXDB_INIT_PORT}
    volumes:
      - ./influx-storage:/var/lib/influxdb2
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    

  mqtt-broker:
    image: eclipse-mosquitto:2.0.15
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt-config:/mosquitto/config
    restart: always

  web-app:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mqtt-broker
